name = "Piccoli_Martinez_2024_JMolLiq"
uuid = "ce6d49cd-32d8-4373-96ba-6a7e27e803e4"
authors = ["viniciuspiccoli <viniciuspiccoli2008@hotmail.com> and contributors"]
version = "0.1.7-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
